title: Project

files:
  sortable: true

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  type:
    label: Type
    type:  text
    width: 1/4
    
  sidebar: 
    label: Sidebar
    type: textarea
    
  text:
    label: Text
    type:  textarea
