title: Site

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
    
  copyright:
    label: Copyright
    type:  textarea
    
  colophon:
    label: Colophon
    type: textarea
    
  twitter:
    label: Twitter
    type: text
    
  instagram: 
    label: Instagram
    type: text
  
  github: 
    label: GitHub
    type: text
  
  linkedin: 
    label: LinkedIn
    type: text